### ISSUE TITLE
多个rpc通讯

### ISSUE THREAD

**Issue by feihua** [helloMJW/seckill#1]
订单里面拿商品信息不是通过rpc去拿的不，现在的架构是不是分库分表是依靠ShardingSphere不，按正常理解是去goods服务里面拿

**Comment by wei98k** [comment]
对的、订单保存到消息队列中、然后通过消费队列订单再通过RPC去调取goods服务拿到完整的商品信息。  分库分表计划使用mycat来实现。

> 订单里面拿商品信息不是通过rpc去拿的不，现在的架构是不是分库分表是依靠ShardingSphere不，按正常理解是去goods服务里面拿

**Comment by feihua** [comment]
OK
